// Code generated by dagger-compiler.  Do not edit.
package de.ur.mi.android.ting.app.fragments;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<NavigationDrawerFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code NavigationDrawerFragment} and its
 * dependencies.
 *
 * Being a {@code Provider<NavigationDrawerFragment>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<NavigationDrawerFragment>} and handling injection
 * of annotated fields.
 */
public final class NavigationDrawerFragment$$InjectAdapter extends Binding<NavigationDrawerFragment>
    implements Provider<NavigationDrawerFragment>, MembersInjector<NavigationDrawerFragment> {
  private Binding<de.ur.mi.android.ting.model.ICategoryProvider> categoryProvider;
  private Binding<BaseFragment> supertype;

  public NavigationDrawerFragment$$InjectAdapter() {
    super("de.ur.mi.android.ting.app.fragments.NavigationDrawerFragment", "members/de.ur.mi.android.ting.app.fragments.NavigationDrawerFragment", NOT_SINGLETON, NavigationDrawerFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    categoryProvider = (Binding<de.ur.mi.android.ting.model.ICategoryProvider>) linker.requestBinding("de.ur.mi.android.ting.model.ICategoryProvider", NavigationDrawerFragment.class, getClass().getClassLoader());
    supertype = (Binding<BaseFragment>) linker.requestBinding("members/de.ur.mi.android.ting.app.fragments.BaseFragment", NavigationDrawerFragment.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(categoryProvider);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<NavigationDrawerFragment>}.
   */
  @Override
  public NavigationDrawerFragment get() {
    NavigationDrawerFragment result = new NavigationDrawerFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<NavigationDrawerFragment>}.
   */
  @Override
  public void injectMembers(NavigationDrawerFragment object) {
    object.categoryProvider = categoryProvider.get();
    supertype.injectMembers(object);
  }

}
