// Code generated by dagger-compiler.  Do not edit.
package de.ur.mi.android.ting.app.activities;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

import android.support.v7.app.ActionBarActivity;

/**
 * A {@code Binding<MainActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code MainActivity} and its
 * dependencies.
 *
 * Being a {@code Provider<MainActivity>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<MainActivity>} and handling injection
 * of annotated fields.
 */
public final class MainActivity$$InjectAdapter extends Binding<MainActivity>
    implements Provider<MainActivity>, MembersInjector<MainActivity> {
  private Binding<de.ur.mi.android.ting.model.IArticleProvider> articleProvider;
  private Binding<de.ur.mi.android.ting.model.ICategoryProvider> categoryProvider;
  private Binding<ActionBarActivity> supertype;

  public MainActivity$$InjectAdapter() {
    super("de.ur.mi.android.ting.app.activities.MainActivity", "members/de.ur.mi.android.ting.app.activities.MainActivity", NOT_SINGLETON, MainActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    articleProvider = (Binding<de.ur.mi.android.ting.model.IArticleProvider>) linker.requestBinding("de.ur.mi.android.ting.model.IArticleProvider", MainActivity.class, getClass().getClassLoader());
    categoryProvider = (Binding<de.ur.mi.android.ting.model.ICategoryProvider>) linker.requestBinding("de.ur.mi.android.ting.model.ICategoryProvider", MainActivity.class, getClass().getClassLoader());
    supertype = (Binding<ActionBarActivity>) linker.requestBinding("members/ActionBarActivity", MainActivity.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(articleProvider);
    injectMembersBindings.add(categoryProvider);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<MainActivity>}.
   */
  @Override
  public MainActivity get() {
    MainActivity result = new MainActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<MainActivity>}.
   */
  @Override
  public void injectMembers(MainActivity object) {
    supertype.injectMembers(object);
  }

}
