// Code generated by dagger-compiler.  Do not edit.
package de.ur.mi.android.ting.app;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class ActivityModule$$ModuleAdapter extends ModuleAdapter<ActivityModule> {
  private static final String[] INJECTS = { "members/de.ur.mi.android.ting.app.activities.MainActivity", "members/de.ur.mi.android.ting.app.activities.LoginActivity", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public ActivityModule$$ModuleAdapter() {
    super(de.ur.mi.android.ting.app.ActivityModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, false /*complete*/, false /*library*/);
  }

  @Override
  public ActivityModule newModule() {
    return new de.ur.mi.android.ting.app.ActivityModule();
  }
}
