// Code generated by dagger-compiler.  Do not edit.
package de.ur.mi.android.ting.app;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class FragmentsModule$$ModuleAdapter extends ModuleAdapter<FragmentsModule> {
  private static final String[] INJECTS = { "members/de.ur.mi.android.ting.app.fragments.NavigationDrawerFragment", "members/de.ur.mi.android.ting.app.fragments.PinListFragment", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public FragmentsModule$$ModuleAdapter() {
    super(de.ur.mi.android.ting.app.FragmentsModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, false /*complete*/, false /*library*/);
  }

  @Override
  public FragmentsModule newModule() {
    return new de.ur.mi.android.ting.app.FragmentsModule();
  }
}
